Ny workspace
mcihadkurel/nyTimes-article pull request #2
Opened 2020-06-25 11:11 UTC by mcihadkurel

New York Times Article is solo project.

2020-06-25 11:44 UTC, elmejdki requested changes
# Great job @mcihadkurel your project looks good :clap: :tophat: , but your repository is terrible you need to make it look professional before you request any code review please do that and then request another code review. :hammer: :hammer_and_pick: :wrench: :toolbox: 

Friendly reminder: You should make sure that your repo looks professional before review. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

## Happy Coding :smiley: 
_If you have any question or you felt stuck at any point feel free to contact me on slack_

2020-06-25 14:02 UTC, elmejdki requested changes
# Great job so far @mcihadkurel :clap: :clap: , your project looks great near to the original page but you need to make some micro :microscope:  changes :hammer: :toolbox:, in order to get it approved. :heavy_check_mark: 

## status: require changes. :recycle: 

- [ ] please fix the header:
### clone:
![image](https://user-images.githubusercontent.com/34653764/85731889-cf087400-b6f2-11ea-83b6-7f9ad3e34d95.png)

### It should look like this:
![image](https://user-images.githubusercontent.com/34653764/85731816-bdbf6780-b6f2-11ea-9143-a6a0ccae3b9a.png)

- [ ] Wrap the new york times logo inside a link tag.
- [ ] the social media links on the bottom overlap over the top menu please use a bigger z-index for the top menu to fix it:
![image](https://user-images.githubusercontent.com/34653764/85732416-41795400-b6f3-11ea-8223-98cb0d2fe7f7.png)

- [ ] **[OPTIONAL]** add some hover styling on the links, for example, make the links change colors when someone hovers over them:
![image](https://user-images.githubusercontent.com/34653764/85732678-7ab1c400-b6f3-11ea-9aa0-828bd5c4f782.png)

- [ ] you have a huge space on the button please remove it:
![image](https://user-images.githubusercontent.com/34653764/85733166-e09e4b80-b6f3-11ea-9283-1b06f6d5f794.png)

- [ ] this time I will not judge you about it, but next time please write good commit messages:
![image](https://user-images.githubusercontent.com/34653764/85733373-0b889f80-b6f4-11ea-803d-cd569bfa57cb.png)
here is a really good [article](https://chris.beams.io/posts/git-commit/) that explains how to write good commit messages, please give it a try.

### Please make all the required changes and then request another code review.
## Happy Coding :tophat: 
_If you have any questions don't hesitate to contact me on slack._

2020-06-25 14:02 UTC, elmejdki commented on README.md
> +
please remove these extras links

2020-06-26 18:11 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @mcihadkurel :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes remaining to carry out before we proceed (see review comment).
##
Lests fix the following minor issues highlighted below 👇 
|[Editor's Pick](https://raw.githack.com/mcihadkurel/nyTimes-article/ny-workspace/index.html) section|[most popular](https://raw.githack.com/mcihadkurel/nyTimes-article/ny-workspace/index.html) section|
|:---:|:---:|
|![clone](https://user-images.githubusercontent.com/22345961/85887898-445a6e80-b7f1-11ea-85ce-83a06a80f64b.png)|![clone-2](https://user-images.githubusercontent.com/22345961/85887911-4a504f80-b7f1-11ea-8ea8-a84686f3e45a.png)|

- [ ] the editor's pick section is not well paced. Kindly reposition it towards the middle of the page. 
- [ ] Work on the most popular section.
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-29 05:49 UTC, mcihadkurel commented
Hi. Thank you for your reply. This project has done for laptop screen sizes, and as I now; it's not required to fix this project for all kinds of screen sizes. Please check this screenshots below. 
![nyss1](https://user-images.githubusercontent.com/65771498/85977312-10479f00-b9e5-11ea-82e7-138f93f4debe.png)
![nyss2](https://user-images.githubusercontent.com/65771498/85977316-1178cc00-b9e5-11ea-96d0-af4635c89485.png)

2020-06-29 06:35 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
### HELLO @mcihadkurel :wave:  AM PETER A TSE AND I WILL BE REVIEWING YOUR PROJECT LETS TAKE A LOOK SHALL WE :eye: 

Great work and you have done everything requested by the previous TSE. One thing prevented me from approving this project kindly fix :arrow_down: 

- [ ] I can see you have the files for linting. However, it seems you forgot to enable it in your repo kindly do that.

**IF YOU HAVE ANY QUESTION FEEL FREE TO REACH OUT TO ME VIA SLACK** :smile: 

### HAPPY CODING :computer:

2020-06-29 13:23 UTC, HADDADSOHAIB approved these changes
### Status: Project Approved :medal_sports: 

### Hi @mcihadkurel :hand: 

### You did great with the project :+1:  You can merge this branch into master

2020-06-29 13:29 UTC, merged